config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  devise_for :candidates, skip: [:passwords], controllers: {
  registrations: "candidate/registrations",
  sessions: 'candidate/sessions'
}

  devise_for :voters, skip: [:passwords], controllers: {
  registrations: "voter/registrations",
  sessions: 'voter/sessions'
}
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_candidate_header.html.erb
<li>
  <%= link_to "HOME", root_path %>
</li>
<li>
  <%= link_to destroy_candidate_session_path, method: :delete do %>
</li>

app/views/layouts/_guest_header.html.erb
<li>
  <%= link_to "HOME", root_path %>
</li>
<li>
  <%= link_to "有権者新規ユーザー登録", new_voter_registration_path %>
</li>
<li>
  <%= link_to "候補者新規ユーザー登録", new_candidate_registration_path %>
</li>
<li>
  <%= link_to "有権者ログイン", new_voter_session_path %>
</li>
<li>
  <%= link_to "候補者ログイン", new_candidate_session_path %>
</li>
<li>
  <%= link_to "管理者ログイン", new_admin_session_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seitomart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if voter_signed_in? %>
        <li>
          <%= render 'layouts/voter_header' %>
        </li>
      <% elsif candidate_signed_in? %>
        <li>
          <%= render 'layouts/candidate_header' %>
        </li>
      <% elsif admin_signed_in? %>
        <il>
          <%= render 'layouts/admin_header' %>
        </il>
      <% else %>
        <il>
          <%= render 'layouts/guest_header' %>
        </il>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>